### ISSUE TITLE
Чей это гитхаб?)

### ISSUE THREAD

**Issue by zhuravlevma** [surreum/learningdart#1]
Ты кто? я же помню такой был у кого-то на одном курсе

**Comment by surreum** [comment]
Привет Максим. Это Вячеслав, мы проходили вместе курс Fullstack в HackerU. )

**Comment by zhuravlevma** [comment]
Вячеслав, ты пропал куда-то с радаров, я только о тебе недавно вспоминал) @zhuravlev_ma это моя телега
